#+TITLE: Инженерная и компьютерная графика

* 2016-09-22

** Адрес
[[mailto:vnveresov@etu.ru][vnveresov@etu.ru]]

** Тема
Владимиру Николаевичу Вересову от лица заочной группы 6005 | Вычислительная Техника (ВТ) с просьбой переслать материал на электронный ящик leti.6005@yandex.ru И вопросом по консультациям И просьбой выслать номер сотового телефона

** Содержание

Здравствуйте.

На первой встрече заочников 2016-09-14,
вы рекомендовали Большаков В.П. Инженерная и компьютерная графика,
но некоторые просят больше теоретического материала.
Отправьте пожалуйста нам *теоретический материал* на электронный ящик [[mailto:leti.6005@yandex.ru][leti.6005@yandex.ru]]

Также многих интересует вопрос консультаций.
Давайте еще раз уточним.
*Консультации по средам с 18:00 в аудитория 5576*, верно?

На прошедшей среде к вам приходило 2 студента, но им не удалось вас разыскать.
Также они звонили на номер телефона 3462917, но не дозвонились.
Возможно ли нам получить *номер сотового телефона* для уточнения времени консультаций?

Заочная группа 6005 | Вычислительная техника (ВТ).
